services:

  mqtt:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: ti-dhome_mqtt_1
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config:ro
    networks:
      - ti-dhome

  nodered:
    image: nodered/node-red:5.0.6
    container_name: ti-dhome_node-red_1
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    networks:
      - ti-dhome
    depends_on:
      - mqtt

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.151.0
    container_name: ti-dhome_victoriametrics_1
    restart: unless-stopped
    ports:
      - "8428:8428"
    command:
      - -retentionPeriod=12
      - -storageDataPath=/victoria-metrics-data
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    networks:
      - ti-dhome
    depends_on:
      - mqtt

volumes:
  mosquitto-data:
  mosquitto-log:
  node-red-data:
  victoria-metrics-data:

networks:
  ti-dhome:
    name: ti-dhome